### ISSUE TITLE
how can i set up telegram (android app) so that only i can add and remove persons from the group

### ISSUE THREAD

**Issue by Sanjar1** [DrKLO/Telegram#1128]

**Comment by Walkman100** [comment]
The only way I know of to do this is to create a group yourself with 200 members, then because of 200 member limit no one else can add people, and only you can kick people.

**Comment by brunobsouzac** [comment]
This is very bad because people within the group are cluttering, changing the group's name and image.

 By creating a group should automatically create a link to the group.

 Owning up to 8 selected moderators. But all very simply. The Telegram is confused, in need of a remodel in usability design. As whatsapp did and was very good but still in need of improvement.

**Comment by DrKLO** [comment]
You can't. There is no server API for that for now.
