### ISSUE TITLE
In App sounds are muted

### ISSUE THREAD

**Issue by droidzone** [DrKLO/Telegram#549]
Even after enabling in app sounds, they are muted while in the main messaging activity. Ideally there should be an option to have low volume beep alerts while a contact who is being responded to, types something while that activity is in focus. This may be an option that can be disabled.

To clarify, there ought to be an option for a low volume alert while the contact with whom chat is initiated types something, even if that activity is in focus and screen is not off. Once again, just like popup notifications, there may an option to have this sound alert while/not screen is off.

**Comment by Sourg** [comment]
Please, add this feature.

**Comment by AUDI-A4** [comment]
Please add this feature

**Comment by AUDI-A4** [comment]
Requesting you to add this feature in next releasevas so many users are requesting.please take into your consideration

**Comment by wp9015362** [comment]
> @DrKLO wrote:
> 
> i know what is it. It's just disabled in opened chats,
> because there is no reason to play something while
> you looking on incoming or outgoing messages.

That's wrong. There _is_ a reason. Let me give you an example:

Let's say you are at home and you are chatting with someone via Telegram-Android using your smartphone and you are doing some other things besides chatting and therefore occasionally have your smartphone lying next to you (i.e. not holding it in your hands).

So now you have your smartphone lying next to you with an open chat in Telegram-Android and you only want to pick up your smartphone (i.e. holding it in your hands) when your conversation partner has sent you a message so that you can reply to it.

But Telegram-Android does not give any audible notification for the newly arrived message.

So you are forced to constantly look at what is happening on the screen of your smartphone to notice if someone has written something or not.

If you would allow to enable an audio notification for incoming messages in open chats though, you no longer would have to constantly look after your smartphone screen.

You could simply wait for the audio notification to appear and then turn your attention to your smartphone.

Do you understand the use case now?

Please, as already mentioned in:

https://github.com/DrKLO/Telegram/issues/734

please implement such an option.

It would be _very_ useful. Not having the option to enable audio notifications for open chats can get annoying very quickly.

So, could you please do something about it?

I mean, as already mentioned in:

https://github.com/DrKLO/Telegram/issues/734#issuecomment-76900974

the iOS version of Telegram already seems to have this feature. So why not just implement it for Telegram-Android as well?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
This is now available in the new Telegram for Android version 2.6.1 from Settings -> Notifications and Sounds -> In-app notifications -> In-Chat Sounds.

But it seems to be buggy as mentioned in:

https://github.com/DrKLO/Telegram/issues/953
