### ISSUE TITLE
Add an option to notify only first unread message?

### ISSUE THREAD

**Issue by petercpg** [DrKLO/Telegram#633]
Sometimes I might be in a meeting or doing something that unavailable to reach the phone, however there might be people in group discussing. 

I found the notification disturbing, but I don't want to turn off notification completely either, hence I'm requesting to add an option to notify once, for the first unread message.

**Comment by Lohoris** [comment]
I was astonished this feature wasn't supported.
It's one of the most basic features an IM can have.

**Comment by Vijfhoek** [comment]
+1 to this feature. It's one of the few advantages that WhatsApp has over Telegram

**Comment by mion00** [comment]
I think this feature is now being discussed in #738

**Comment by PioneerAxon** [comment]
Since @DrKLO seemed not to be interested in merging my patches from #738 at all, I have got it merged in Plus Messanger[1].
You can probably switch to Plus messenger if this feature is important for your usecase.
@mion00 @Vijfhoek @Lohoris @Zequez @petercpg @Aokromes @stefan-niedermann 

Hope this helps.. :)

[1] : https://play.google.com/store/apps/details?id=org.telegram.plus

**Comment by DrKLO** [comment]
Smart notifications implemented in 2.8.0.
