### ISSUE TITLE
[FEATURE REQUEST] Save voice messages

### ISSUE THREAD

**Issue by devianpctek** [DrKLO/Telegram#809]
As tittle suggests, is it possible to add this feature to Telegram?

**Comment by DrKLO** [comment]
It's already saving to /external storage/Telegram/audio.

**Comment by devianpctek** [comment]
Yeah, not really intuitive for the average user thought, I was thinking something like selecting the voice message (which I already know the message I want, instead of going through all the files on the folder trying to look for it) then just save it (or just copy i or soft link it to the original in order to save space) somewhere else like on the Download folder, I think this makes it more easy to find in the way that this messages will be only the ones we want to have handy, I hope I made my self clear.

![photo_2015-02-06_07-24-02](https://cloud.githubusercontent.com/assets/1848859/6079922/2f518f9e-add1-11e4-98b7-4b8056881a0b.jpg)

**Comment by luxvio** [comment]
I have a few questions regarding voice messages @DrKLO :         
         
I haven't found in the protocol page of telegram.org a part where it describes what are the specifications around voice messages. For example if there is a audio size limit or in lenght ... if there's a limitation on what modes of Opus are permitted (CELT/SILK/Hybrid), vbr or cbr, blah or if there's no imposed limitations.           
         
Having this clarified would be quite awesome, because for example in the tdesktop app could be really useful to have the chance of sending voice notes ... from mic, and from our very own opus files that conforms to the telegram standards (similar to sending webp encoded images as files to have them seen as stickers).        
        
Ty for your time !

**Comment by DrKLO** [comment]
@luxvio there is no any specification for voice messages. Both Android and iOS apps using native opus library so it will play any mode of it. Also Android will play audio message of any other audio codec which android can support, even if it's mp3 of wav. File size is limited to 1.5 GB.

**Comment by luxvio** [comment]
@DrKLO → So I can craft a voice message with mp3 ... and it will be seen as a regular voice message (not a file) in the android client and such?                
               
Thank you so much for your time. Very clarifying

**Comment by DrKLO** [comment]
@luxvio yes, it will look like voice message, but maybe not all clients will be able to play this.

**Comment by Kasramvd** [comment]
I use liniux and have not `/external storage` directory! how can I access to audio files with a bot?
